map_type: costmap

obstacle_range: 2.0
raytrace_range: 1.9
footprint: [[0.2, 0.1], [0.2, -0.1], [-0.2, -0.1], [-0.2, 0.1]]


publish_cost_grid: true


# maximum allowed delay b/w transformation
transform_tolerance: 0.2

# inflation_radius: 0.5

# useful for visualizing the costmap in rviz
publish_frequency: 50 

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}