global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   static_map: true
   rolling_window: false

   allow_unknown: true
   use_dijkstra: true
   use_quadratic: true
   use_grid_path: false
   old_navfn_behavior: false
   visualize_potential: true

   cost_factor: 0.05
   neutral_cost: 66
   lethal_cost: 253
